.\" Generated with Ronnjs 0.3.8
.\" http://github.com/kapouer/ronnjs/
.
.TH "SPOT" "1" "March 2012" "" ""
.
.SH "NAME"
\fBspot\fR \-\- full\-text bash search utility
.
.SH "Synopsis"
   spot [\-s|\-\-sensitive] [\-i|\-\-insensitive]
        [\-C|\-\-no\-colors] [\-L|\-\-no\-linenums]
        [\-h|\-\-help] [directory] [term \.\.\.]
.
.SH "Description"
  By default unless \fB\-\-sensitive\fR or \fB\-\-insensitive\fR is
  specified \fBspot(1)\fR implies \fB\-\-sensitive\fR when an
  uppercased character is present in the search string\.